language: java
install: true

os: linux
dist: trusty
jdk: openjdk11

script:
  - chmod +x ./gradlew
  - ./gradlew bootJar -s
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  skip_cleanup: true
  on:
    tags: true
